stages:
  preprocess:
    cmd: python ./src/process_data.py
    deps:
    - ./src/process_data.py
    - ./raw_data/ames_unprocessed_data.csv
    - ./config/config.yaml  # Add this line
    outs:
    - ./processed_data/test_processed.csv
    - ./processed_data/train_processed.csv
    - ./artifacts/preprocessor.pkl
  train:
    cmd: python ./src/train.py
    deps:
    - ./processed_data/test_processed.csv
    - ./processed_data/train_processed.csv
    - ./src/train.py
    - ./config/config.yaml  # Add this line
    outs:
    - ./saved_models/random_forest_model.pkl
    - ./artifacts/feature_importances.png
