version: '3'

services:
  ml-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: ml-project-image
    container_name: ml-project-container
    ports:
      - "8080:8080"
    volumes:
      # Mount data directories for persistence
      - ../raw_data:/app/raw_data
      - ../processed_data:/app/processed_data
      - ../artifacts:/app/artifacts
      - ../saved_models:/app/saved_models
    environment:
      - PYTHONUNBUFFERED=1
      # Add any environment variables your application needs
    command: python ./src/main.py
    # Uncomment to enable health check if your app has a health endpoint
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3